
server:
  port: 8081
spring:
  profiles:
    active: dev
---
server:
  port: 8083
spring:
  profiles: dev

---
server:
  port: 8084
spring:
  profiles: prod

#person:
#  age: 18
#  boss: false
#  birth: 2020/01/19
#  maps: {k1: v1,k2: l2}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: 小狗
#    age: 2
#  last-name: zhangsan
